# Generated by Django 4.0.5 on 2022-06-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonnybank_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
        migrations.RenameModel(
            old_name='RoomImages',
            new_name='RoomImage',
        ),
    ]
