# Generated by Django 4.0.5 on 2022-06-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonnybank_app', '0002_rename_news_new_rename_promotions_promotion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
        migrations.RenameModel(
            old_name='Promotion',
            new_name='Promotions',
        ),
        migrations.RenameModel(
            old_name='RoomImage',
            new_name='RoomImages',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='promotions',
            options={'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='roomimages',
            options={'verbose_name_plural': 'RoomImages'},
        ),
    ]
