# Generated by Django 4.0.5 on 2022-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonnybank_app', '0008_rename_name_contact_first_name_contact_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='checkin',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='checkout',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
