# Generated by Django 4.0.5 on 2022-07-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonnybank_app', '0009_alter_contact_checkin_alter_contact_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimages',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomImages',
        ),
    ]
