# Generated by Django 4.0.5 on 2022-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonnybank_app', '0011_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='quote',
            field=models.TextField(max_length=800),
        ),
    ]
