# Generated by Django 4.0.5 on 2022-07-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonnybank_app', '0013_alter_review_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='quote',
            field=models.TextField(max_length=1200),
        ),
    ]
