# Generated by Django 4.0.5 on 2022-08-18 15:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonnybank_app', '0016_alter_event_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
